apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-deployment
  template:
    metadata:
      labels:
        app: python-deployment
    spec:
      containers:
      - name: python-redis
        image: seanlam751/presto-redis-python:latest