apiVersion: apps/v1
kind: Deployment
metadata:
  name: presto-coordinator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: presto-coordinator
  template:
    metadata:
      labels:
        app: presto-coordinator
    spec:
      containers:
      - name: presto
        image: prestodb/presto:latest
        ports:
            - containerPort: 8080