apiVersion: v1
kind: ConfigMap
metadata:
  name: presto-config
data:
  config.properties: |
    # Your custom config.properties content
    coordinator=true
    node-scheduler.include-coordinator=false
    http-server.http.port=8080
    query.max-memory=5GB
    query.max-memory-per-node=1GB
    discovery-server.enabled=true
    discovery.uri=http://example.net:8080
  jvm.config: |
    # Your custom jvm.config content
    -server
    -Xmx8G
    -XX:+UseG1GC
  catalog/redis.properties: |
    connector.name=redis
    
