apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-redis-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-redis
  template:
    metadata:
      labels:
        app: ubuntu-redis
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:20.04
        command:
        - /bin/sh
        - -c
        - |
          apt update && \
          apt install -y lsb-release curl gnupg redis && \
          curl -fsSL https://packages.redis.io/gpg | sudo gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg && \
          echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/redis.list && \
          apt-get update
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-presto-coordinator-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-presto-coordinator
  template:
    metadata:
      labels:
        app: ubuntu-presto-coordinator
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:20.04
        command:
        - /bin/sh
        - -c
        - |
          apt update && \
          apt install -y python-is-python3 wget openjdk-11-jre-headless && \
          wget https://repo1.maven.org/maven2/com/facebook/presto/presto-server/0.287/presto-server-0.287.tar.gz && \
          tar -xzvf presto-server-0.287.tar.gz && \
          cd presto-server-0.287 && \
          ./bin/launcher start
