version:
  java: 11
  presto: 0.288
  mongo: 7.0.12

host:
  redis: redis-service.default.svc.cluster.local
port:
  redis: 6379
  mongo: 27017

replicas:
  redis: 2
  rockylinux: 2
  ubuntu: 1
  mongo: 1

presto:
  mode: cluster
  coordinator:
    replicas: 1
  worker:
    replicas: 2
  catalog:
    redis: |-
      connector.name=redis
      redis.table-names=table
      redis.nodes=redis-service.default.svc.cluster.local:6379
  livenessProbe:
    initialDelaySeconds: 90
  readinessProbe:
    initialDelaySeconds: 90
