apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
  namespace: {{ .Release.Namespace }}
data:
  redis-service: redis-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-config
  namespace: {{ .Release.Namespace }}
data:
  init-mongo.js: |
    rs.initiate();

    // Create a collection and insert some documents
    // do not name the database with any capital letter
    db.testcollection.insertMany([
      { name: "Alice", age: 30 },
      { name: "Bob", age: 25 },
      { name: "Carol", age: 35 }
    ]);

    print("Database initialized with test data.");