apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
  namespace: {{ .Release.Namespace }}
data:
  redis-service: redis-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-config
  namespace: {{ .Release.Namespace }}
data:
  init-mongo.js: |
    rs.initiate(
        {
          _id: "rs0",
          members: [
            { _id: 0, host: "mongodb-replica-0.mongo-service.default.svc.cluster.local:27017" },
            { _id: 1, host: "mongodb-replica-1.mongo-service.default.svc.cluster.local:27017" }
          ]
        }
    );
    db = db.getSiblingDB('testdb');  // Create or switch to the 'testdb' database

    // Create a collection and insert some documents
    db.myCollection.insertMany([
      { name: "Alice", age: 30 },
      { name: "Bob", age: 25 },
      { name: "Carol", age: 35 }
    ]);

    print("Database initialized with test data.");
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
  namespace: {{ .Release.Namespace }}
data:
  mongod.conf: |
    storage:
      dbPath: /data/db
    net:
      bindIp: 0.0.0.0
      port: 27017
    replication:
      replSetName: rs0