apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas.mongo }}
  selector:
    matchLabels:
      app: mongo-deployment
  template:
    metadata:
      labels:
        app: mongo-deployment
    spec:
      initContainers:
      - name: mongo-init
        image: mongo:{{ .Values.version.mongo }}
        command: ['sh', '-c', 'until mongosh --host mongo-service --eval "print(\"waited for connection\")"; do sleep 5; done; mongosh --host mongo-service --eval "db.adminCommand( { shutdown : 1} );rs.initiate()"']
      containers:
      - name: mongo
        image: mongo:{{ .Values.version.mongo }}
        ports:
            - containerPort: {{ .Values.port.mongo }}
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: mongo-deployment
  ports:
    - protocol: TCP
      port: {{ .Values.port.mongo }}
      targetPort: {{ .Values.port.mongo }}