apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-replica
  namespace: default
spec:
  serviceName: mongo
  replicas: 2
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
        selector: mongo
    spec:
      terminationGracePeriodSeconds: 30
      serviceAccount: mongo-account
      containers:
      - name: mongodb
        image: mongo:{{ .Values.version.mongo }}
        command: ["/bin/sh"]
        args: ["-c", "mongod --replSet=rs0 --bind_ip_all"]
        resources:
          limits:
            cpu: 1
            memory: 1500Mi
          requests:
            cpu: 1
            memory: 1000Mi
        ports:
        - name: mongo-port
          containerPort: 27017
        volumeMounts:
        - name: mongodb-data
          mountPath: /data
        - name: mongo-configmap
          mountPath: /config
          readOnly: true
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongo-pvc
      - name: mongo-configmap
        configMap:
          name: mongo-configmap
          items:
          - key: mongo.conf
            path: mongo.conf

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: {{ .Values.port.mongo }}
      targetPort: {{ .Values.port.mongo }}