apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-replica
  namespace: default
spec:
  serviceName: mongo-service
  replicas: 2
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: mongodb
        image: mongo:{{ .Values.version.mongo }}
        command:
        - "mongod"
        - "--config"
        - "/etc/mongod.conf"
        resources:
          limits:
            cpu: 1
            memory: 1500Mi
          requests:
            cpu: 1
            memory: 1000Mi
        ports:
        - name: mongo-port
          containerPort: {{ .Values.port.mongo }}
        volumeMounts:
        - name: mongo-config
          mountPath: /etc/mongod.conf
          subPath: mongod.conf
        - name: mongo-init
          mountPath: /docker-entrypoint-initdb.d
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongo-pvc
      - name: mongo-init
        configMap:
          name: mongo-init-config
      - name: mongo-config
        configMap:
          name: mongo-config
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: {{ .Values.port.mongo }}
      targetPort: {{ .Values.port.mongo }}

