apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocky-linux-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas.rockylinux }}
  selector:
    matchLabels:
      app: rockylinux
  template:
    metadata:
      labels:
        app: rockylinux
    spec:
      containers:
      - name: rockylinux
        image: rockylinux:9
        command:
          - "/bin/bash"
          - "-c"
        args:
          - |
            echo "[mongodb-org-7.0]
            name=MongoDB Repository
            baseurl=https://repo.mongodb.org/yum/redhat/9/mongodb-org/7.0/x86_64/
            gpgcheck=1
            enabled=1
            gpgkey=https://pgp.mongodb.com/server-7.0.asc" > /etc/yum.repos.d/mongodb-org-7.0.repo && \

            yum install -y mongodb-org && \

            sleep infinity