apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas.ubuntu }}
  selector:
    matchLabels:
      app: ubuntu-deployment
  template:
    metadata:
      labels:
        app: ubuntu-deployment
    spec:
      containers:
        - name: ubuntu
          image: ubuntu:20.04
          command:
            - "/bin/bash"
            - "-c"
          args:
            - |
              echo "nameserver 8.8.8.8" | tee /etc/resolv.conf > /dev/null
              apt-get update && \
              apt-get install -y redis wget openjdk-{{ .Values.version.java }}-jdk-headless less && \
              wget -q https://repo1.maven.org/maven2/com/facebook/presto/presto-cli/{{ .Values.version.presto }}/presto-cli-{{ .Values.version.presto }}-executable.jar && \
              mv presto-cli-{{ .Values.version.presto }}-executable.jar presto && \
              chmod +x presto && \
              wget https://downloads.mongodb.com/compass/mongodb-mongosh_{{ .Values.version.mongosh }}_amd64.deb
              dpkg -i mongodb-mongosh_{{ .Values.version.mongosh }}_amd64.deb
              sleep infinity
          env:
            - name: REDIS_HOST
              value: "redis-service"