apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocky-linux-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rockylinux
  template:
    metadata:
      labels:
        app: rockylinux
    spec:
      containers:
      - name: rockylinux
        image: rockylinux:9
        command: ["sleep"]
        args: ["infinity"]