apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas.ubuntu }}
  selector:
    matchLabels:
      app: ubuntu-deployment
  template:
    metadata:
      labels:
        app: ubuntu-deployment
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:20.04
        command:
          - "/bin/bash"
          - "-c"
        args:
          - |
            apt-get update && \
            apt-get install -y redis wget openjdk-11-jdk-headless && \ 
            wget -q https://repo1.maven.org/maven2/io/trino/trino-cli/{{ .Values.version.trino }}/trino-cli-{{ .Values.version.trino }}-executable.jar && \
            mv trino-cli-{{ .Values.version.trino }}-executable.jar trino && \
            chmod +x trino && \
            sleep infinity
        env:
          - name: REDIS_HOST
            value: "redis-service"
